### ISSUE TITLE
Preview on hover for HEVC videos

### ISSUE THREAD

**Issue by mf35** [fupdec/Adult-Video-Database#18]
With VLC integration HEVC videos are readable, which is fantastic, but the animated preview still doesn't work when you hover with your mouse on a such HEVC's video card.

**Comment by fupdec** [comment]
unfortunately I cannot add a VLC player to each video card because it is very resource intensive. I think it would be better to add something like a small icon to the video card, which cannot play the video through the html5 player. and on hovering over it, a small window with a VLC player will appear in which the preview will play.
or completely abandon the html5 player and implement the VLC player for playing previews.

this is a pretty daunting task, and most videos are already supported. I will return to this task later when the rest of the problems will be resolved.

**Comment by mf35** [comment]
Oh ok, i understand the technical concern here.

**Comment by fupdec** [comment]
I am closing this issue because the application is now using the HTML5 player.
