### ISSUE TITLE
Performer sorting by "hotness"

### ISSUE THREAD

**Issue by draftvader** [fupdec/Adult-Video-Database#89]
Having spent some time growing my database I am enjoying seeing how the "hotness" reflects my own "feelings" ;)

It would be nice to have an option to sort by "hotness"

**Comment by fupdec** [comment]
I've added a new type of meta: rating. You can manually set a performer hotness rating and sort them by that rating. I am closing this issue for now. If you are also interested in the meter, you can open the issue.

**Comment by draftvader** [comment]
Forgive my early lack of knowledge on the "meter" terminology. That was what I meant. Sorting by "meter". Obviously an enhancement for when it returns.

**Comment by fupdec** [comment]
Previously, the meter was generated automatically every time the page was opened. The generation process itself was simple, but to calculate the number of meters, the tags were used that were assigned to the video, to which the performer was also assigned. And collecting all the tags from the video was slow, even for one performer. Therefore, the collection of tags did not take place when the page was opened, but in advance, when all information about the video was updated (there is a special setting - to update data from the video). Therefore, I want to give up the meter. Perhaps I will create a poll for users whether they need a meter or are they willing to manually set a hotness rating for their performers. By the way, I have already done this on my test build of the application. I want to drop the meter for several more reasons:
1) the principle of its operation is difficult to understand and I do not know how to make it easier.
2) for it to work, you need to set a value for each tag.
3) it is only relevant when the data from the video is updated.
4) it is impossible to sort by its value, because it is generated every time anew and its value is not saved anywhere.
5) confusion arises with the names in the new meta system.
6) etc.

I understand that the things that the application does automatically based on user data are useful. but in the case of the meter, there are a lot of inconveniences. and in the future I plan to add interesting features that will visually show user information.

**Comment by draftvader** [comment]
Yes, that would be a very intensive operation that would lower the user experience. I agree with putting it on the back-burner until your brain tells you a better way :)
